name: wildfire3.7
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7.7
  - pip=20.0.2
  - pytorch=1.4.0
  - pip:
    - black==19.10b0
    - callisto==0.7
    - click==7.0
    - dask==2.14.0
    - dask-jobqueue==0.7.1
    - ipywidgets==7.5.1
    - jupyterlab==2.1.0
    - matplotlib==3.1.1
    - netcdf4==1.5.3
    - pandas==0.25.3
    - Pillow==7.1.1
    - pip-tools==4.5.1
    - pydocstyle==4.0.1
    - pylint==2.4.4
    - pytest==5.4.1
    - pytest-cov==2.8.1
    - scipy==1.4.1
    - s3fs==0.4.0
    - xarray==0.14.0
