#!/bin/bash
set -euxo pipefail
# -e exit on first error
# -u exit if variable is not set
# -x print each command run to stdout
# -o pipefail return the error status of the last command to exit

conda env create -f environment.yml
conda activate wildfire3.7
python setup.py install
callisto --path=$PWD
