name: CI

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Set up virtual environment
      uses: goanpeca/setup-miniconda@v1
      with:
        environment-file: environment.yml
        activate-environment: wildfire3.7
        auto-activate-base: false
    - name: Linting, unit, and integration tests
      shell: bash -l {0}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        conda info --envs
        conda list
        conda activate wildfire3.7
        conda info --envs
        conda list
        scripts/test-it
