name: CI

on: pull_request

jobs:
    ci-ubuntu:
      name: CI on Ubuntu
      runs-on: ubuntu-latest
      steps:
      - name: Test on ubuntu
        run: scripts/test
    ci-mac:
      name: CI on MacOS
      runs-on: macOS-latest
      steps:
      - name: Test on mac
        run: scripts/test
    
