name: CI

on: pull_request

jobs:
  build:
    runs-on: ${{ matrix.os }}
    python-version: 3.6
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test
      run: scripts/test
